# Generated by Django 5.1 on 2024-08-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flan',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
